### ISSUE TITLE
GitKraken - fail to start

### ISSUE THREAD

**Issue by floriandd2ba** [winbench/bench#133]
#### GitKraken don't start at the launcher.

**Start with PowerShell Show this error:**

````
PS H:\winbench\lib\apps\bench\gitkraken>
Node started time: 1529711047468
{ Error: ENOENT: no such file or directory, scandir 'H:\winbench\home\AppData\Roaming\.gitkraken\profiles'
    at Object.fs.readdirSync (fs.js:910:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:578:28)
    at getProfileGuids (H:\winbench\lib\apps\bench\gitkraken\resources\app.asar\src\appBootstrap\upgradeScripts\versionScripts\v2_2_0.js:38:32)
    at Object.upgradeToVersion220 [as v2.2.0] (H:\winbench\lib\apps\bench\gitkraken\resources\app.asar\src\appBootstrap\upgradeScripts\versionScripts\v2_2_0.js:56:20)
    at lastPromise.then (H:\winbench\lib\apps\bench\gitkraken\resources\app.asar\src\appBootstrap\upgradeScripts\index.js:17:197)
    at <anonymous>
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'H:\\winbench\\home\\AppData\\Roaming\\.gitkraken\\profiles' }
````

**I solved this with this Change in "*\lib\applibs\default\scripts\bench\gitkraken.setup.ps1"**
````
$profilesDir = [IO.Path]::Combine((Get-ConfigValue "AppDataDir"), ".gitkraken\profiles")

if (!(Test-Path $profilesDir))
{
    $_ = mkdir $profilesDir
}
````

**Comment by mastersign** [comment]
Thanks for the patch. I updated the default app library.
Please update the app libraries in your Bench environment to use the fixed script.

_Setup Dialog_ &rarr; _Setup_ &rarr; _Update App Libraries_

Then reinstall the GitKraken app.
